log_level: debug
cpu_affinity: [1]

buffer_depth: 10
sample_length: 1024
sizeof_float: 4

gen_data:
  kotekan_stage: testDataGenFloat
  network_out_buf: input_buf
  type: random
  seed: 42
  samples_per_data_set: sample_length
  rand_max: 100

input_buf:
  kotekan_buffer: standard
  metadata_pool: meta_pool
  num_frames: buffer_depth
  frame_size: sample_length * sizeof_float

meta_pool:
  kotekan_metadata_pool: chimeMetadata
  num_metadata_objects: 5 * buffer_depth

